### ISSUE TITLE
LICENSES.chromium.html handling

### ISSUE THREAD

**Issue by tysenmoore-xse** [atom/brightray#199]
I have questions how the `LICENSES.chromium.html` should be handled.  From what I can tell, please correct me if I'm wrong, the file is part of the `vendor/download/libchromiumcontent`.  However, there is a script, `vendor/libchromiumcontent/tools/licenses.py` that appears to create the same content.  However, it seems the script is never called--at least when used from Electron.  How should the `LICENSES.chromium.html` file be handled?  Should we rely on the downloaded file or use the script to somehow create our own?

The reason I ask is because the license file contains some LGPL v3 packages (`talloc`, and `liblouis` (`Braille Translation Library`)).  When I attempt to grep sources I see no use of `talloc`.  I am trying to understand how the license file is created so I can tell if it truly reflects the contents within Brightray.  I need to know if these packages are actually used.  Any information would be helpful.  Thanks.

**Comment by zcbenz** [comment]
The `LICENSES.chromium.html` was created when creating prebuilt binaries for https://github.com/atom/libchromiumcontent, it is not called by Electron.

This file includes licenses of all source files of Chromium(https://code.google.com/p/chromium/codesearch), instead of Electron or brightray, there are a few GPL licensed libraries, but they are only used by Chromium for testing or build tools, they are not included in the final product.
